//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ДЭ1
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcademicLoad
    {
        public decimal ID { get; set; }
        public decimal DisciplineID { get; set; }
        public decimal GroupID { get; set; }
        public decimal TeacherID { get; set; }
        public decimal AcademicYearID { get; set; }
        public decimal Semester { get; set; }
    
        public virtual AcademicYear AcademicYear { get; set; }
        public virtual Discipline Discipline { get; set; }
        public virtual Group Group { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
